### PR TITLE
support local OpenAI-like server

### PR DESCRIPTION
**Pull request by namin**

### CODE REVIEW

**Comment by alishobeiri** [comment]
Hi Nada, 

Thank you so much for the pull request, if it's okay with you I have some UI changes that I will integrate with yours so a user can set the URL in the UI as well. 

Will add those shortly and approve. Thank you again for opening up the PR!

**Comment by namin** [comment]
Sounds great, thank you!

**Comment by rambalachandran** [comment]
One recommendation is to add and test support for openrouter, which provides openai equivalent api but can provide access yo a wide range of models including claude, llama among others

https://openrouter.ai/

**Comment by alishobeiri** [comment]
Just realized it is easier to do this if I merge cause otherwise I need to submit a PR to your fork to be able to have it submitted here :)

**Pull request merged**
